# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [97]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [98]:
### [your code here]
print(np.version.version)
print(np.version.full_version)

2.3.5
2.3.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [99]:
##import random as rnd
### 1
a=np.random.rand(2,3,5)
### 2
a2=np.random.randint(1,10,size=(2,3,5))
### 3
a3=np.random.random((2, 3, 5))



### 4. Print a.


In [100]:
print(a)
print("-"*90)
print(a2)
print("-"*90)
print(a3)





[[[0.652945   0.29581449 0.37530121 0.10449578 0.42569161]
  [0.85814659 0.48540581 0.13594951 0.00466293 0.39866095]
  [0.72928503 0.37207982 0.35342525 0.28943092 0.69067431]]

 [[0.42625339 0.95424983 0.55631081 0.1492618  0.71657275]
  [0.08042229 0.73867362 0.27485525 0.63343807 0.99209998]
  [0.50786185 0.35917928 0.63309096 0.75541678 0.51929796]]]
------------------------------------------------------------------------------------------
[[[3 4 5 6 2]
  [5 1 6 2 5]
  [6 1 2 7 2]]

 [[5 1 1 8 9]
  [1 8 3 3 3]
  [4 8 4 6 9]]]
------------------------------------------------------------------------------------------
[[[0.22683393 0.51172904 0.80685161 0.98468703 0.45514499]
  [0.42812469 0.12172588 0.99467758 0.26494121 0.6514715 ]
  [0.95392254 0.89133532 0.22823541 0.49037341 0.18106612]]

 [[0.12954387 0.88398142 0.29425534 0.54477211 0.13467466]
  [0.83318535 0.8490739  0.65442828 0.4987682  0.81162973]
  [0.73444889 0.17098747 0.58753861 0.91694923 0.45863217]]]


### 5. Create a 5x3x2 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [101]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [102]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [103]:
### [your code here]
print("Do a and b have the same size?",a.size==b.size)
print("a size: ",a.size)
print("b size: ",b.size)


Do a and b have the same size? True
a size:  30
b size:  30



### 8. Are you able to add a and b? Why or why not?


In [104]:
### [your code here]
### NO, because a and b do not have the same form (2x3x5) versus (5x2x3)
print("\n -a-The dimension is:", a.ndim," The shape is:", a.shape, "The size is:", a.size)
print(a)
print("\n-b-the dimension is:", b.ndim," The shape is:", b.shape, "The size is:", b.size)
print(b)


 -a-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30
[[[0.652945   0.29581449 0.37530121 0.10449578 0.42569161]
  [0.85814659 0.48540581 0.13594951 0.00466293 0.39866095]
  [0.72928503 0.37207982 0.35342525 0.28943092 0.69067431]]

 [[0.42625339 0.95424983 0.55631081 0.1492618  0.71657275]
  [0.08042229 0.73867362 0.27485525 0.63343807 0.99209998]
  [0.50786185 0.35917928 0.63309096 0.75541678 0.51929796]]]

-b-the dimension is: 3  The shape is: (5, 2, 3) The size is: 30
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [105]:
### [your code here]
print("\n-b-the dimension is:", b.ndim," The shape is:", b.shape, "The size is:", b.size)
c= np.transpose(b,(1,2,0))
print("\n-c-The dimension is:", c.ndim," The shape is:", c.shape, "The size is:", c.size)
print("\n -a-The dimension is:", a.ndim," The shape is:", a.shape, "The size is:", a.size)

print(a)
print(c)




-b-the dimension is: 3  The shape is: (5, 2, 3) The size is: 30

-c-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30

 -a-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30
[[[0.652945   0.29581449 0.37530121 0.10449578 0.42569161]
  [0.85814659 0.48540581 0.13594951 0.00466293 0.39866095]
  [0.72928503 0.37207982 0.35342525 0.28943092 0.69067431]]

 [[0.42625339 0.95424983 0.55631081 0.1492618  0.71657275]
  [0.08042229 0.73867362 0.27485525 0.63343807 0.99209998]
  [0.50786185 0.35917928 0.63309096 0.75541678 0.51929796]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [106]:
### [your code here]
d=a+c
print(d)
print("\n -d-The dimension is:", d.ndim," The shape is:", d.shape, "The size is:", d.size)

## Now work because a and c have the same structure

print("\n -a-The dimension is:", a.ndim," The shape is:", a.shape, "The size is:", a.size)
print("\n-c-The dimension is:", c.ndim," The shape is:", c.shape, "The size is:", c.size)
print("\n Have -a- & -c- the same shape? ", a.shape==c.shape)


[[[1.652945   1.29581449 1.37530121 1.10449578 1.42569161]
  [1.85814659 1.48540581 1.13594951 1.00466293 1.39866095]
  [1.72928503 1.37207982 1.35342525 1.28943092 1.69067431]]

 [[1.42625339 1.95424983 1.55631081 1.1492618  1.71657275]
  [1.08042229 1.73867362 1.27485525 1.63343807 1.99209998]
  [1.50786185 1.35917928 1.63309096 1.75541678 1.51929796]]]

 -d-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30

 -a-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30

-c-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30

 Have -a- & -c- the same shape?  True



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [107]:
### [your code here]

print("-a-\n",a)

print("-d-\n",d)

##  "d " is the "a" matrix that we have added 1 to all the elements

-a-
 [[[0.652945   0.29581449 0.37530121 0.10449578 0.42569161]
  [0.85814659 0.48540581 0.13594951 0.00466293 0.39866095]
  [0.72928503 0.37207982 0.35342525 0.28943092 0.69067431]]

 [[0.42625339 0.95424983 0.55631081 0.1492618  0.71657275]
  [0.08042229 0.73867362 0.27485525 0.63343807 0.99209998]
  [0.50786185 0.35917928 0.63309096 0.75541678 0.51929796]]]
-d-
 [[[1.652945   1.29581449 1.37530121 1.10449578 1.42569161]
  [1.85814659 1.48540581 1.13594951 1.00466293 1.39866095]
  [1.72928503 1.37207982 1.35342525 1.28943092 1.69067431]]

 [[1.42625339 1.95424983 1.55631081 1.1492618  1.71657275]
  [1.08042229 1.73867362 1.27485525 1.63343807 1.99209998]
  [1.50786185 1.35917928 1.63309096 1.75541678 1.51929796]]]



### 12. Multiply a and c. Assign the result to e.


In [108]:
### [your code here]
e= a*c
print("-e-\n",e)
print("\n-e-The dimension is:", e.ndim," The shape is:", e.shape, "The size is:", e.size)


-e-
 [[[0.652945   0.29581449 0.37530121 0.10449578 0.42569161]
  [0.85814659 0.48540581 0.13594951 0.00466293 0.39866095]
  [0.72928503 0.37207982 0.35342525 0.28943092 0.69067431]]

 [[0.42625339 0.95424983 0.55631081 0.1492618  0.71657275]
  [0.08042229 0.73867362 0.27485525 0.63343807 0.99209998]
  [0.50786185 0.35917928 0.63309096 0.75541678 0.51929796]]]

-e-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30




### 13. Does e equal to a? Why or why not?


In [109]:
### [your code here]
print("Does e equal to a?",e==a)

### ## "e" is the same as "a" since we have multiplied a by an array of ones (c) so we have multiplied each value of "a" by 1 and multiplying a value by 1 does not change the value.


Does e equal to a? [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [110]:
### [your code here]
d_max = np.max(d); print("-d- Max Value:", d_max)
d_min = np.min(d); print("-d- Min Value:", d_min)
d_mean = np.mean(d); print("-d- Mean of Values:", d_mean)

-d- Max Value: 1.992099983874926
-d- Min Value: 1.0046629346636982
-d- Mean of Values: 1.482298461389874



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [111]:
### [your code here]
f=np.empty((2,3,5))
print("-f-\n",f)
print("\n-f-The dimension is:", f.ndim," The shape is:", f.shape, "The size is:", f.size)
print("-d-\n",d)



-f-
 [[[0.652945   0.29581449 0.37530121 0.10449578 0.42569161]
  [0.85814659 0.48540581 0.13594951 0.00466293 0.39866095]
  [0.72928503 0.37207982 0.35342525 0.28943092 0.69067431]]

 [[0.42625339 0.95424983 0.55631081 0.1492618  0.71657275]
  [0.08042229 0.73867362 0.27485525 0.63343807 0.99209998]
  [0.50786185 0.35917928 0.63309096 0.75541678 0.51929796]]]

-f-The dimension is: 3  The shape is: (2, 3, 5) The size is: 30
-d-
 [[[1.652945   1.29581449 1.37530121 1.10449578 1.42569161]
  [1.85814659 1.48540581 1.13594951 1.00466293 1.39866095]
  [1.72928503 1.37207982 1.35342525 1.28943092 1.69067431]]

 [[1.42625339 1.95424983 1.55631081 1.1492618  1.71657275]
  [1.08042229 1.73867362 1.27485525 1.63343807 1.99209998]
  [1.50786185 1.35917928 1.63309096 1.75541678 1.51929796]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [112]:
### [your code here]

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]): 
            x_d=d[i][j][k]
            if x_d > d_min and x_d < d_mean:
                f[i][j][k]=25
            elif x_d > d_mean and x_d < d_max:
                f[i][j][k]=75
            elif x_d == d_mean:
                f[i][j][k]=50
            elif x_d == d_min:
                f[i][j][k]=0
            elif x_d == d_max:
                f[i][j][k]=100
   

print("-f-\n",f)

-f-
 [[[ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.   0.  25.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  75.  25.  75. 100.]
  [ 75.  25.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]
print("-d-\n",d)
print("-f-\n",f)

print("-d- Max Value:", d_max)
print("-d- Min Value:", d_min)
print("-d- Mean of Values:", d_mean)

### YES, I have!!

-d-
 [[[1.652945   1.29581449 1.37530121 1.10449578 1.42569161]
  [1.85814659 1.48540581 1.13594951 1.00466293 1.39866095]
  [1.72928503 1.37207982 1.35342525 1.28943092 1.69067431]]

 [[1.42625339 1.95424983 1.55631081 1.1492618  1.71657275]
  [1.08042229 1.73867362 1.27485525 1.63343807 1.99209998]
  [1.50786185 1.35917928 1.63309096 1.75541678 1.51929796]]]
-f-
 [[[ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.   0.  25.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  75.  25.  75. 100.]
  [ 75.  25.  75.  75.  75.]]]
-d- Max Value: 1.992099983874926
-d- Min Value: 1.0046629346636982
-d- Mean of Values: 1.482298461389874


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [122]:
### [your code here]
bonus=np.empty((2,3,5),dtype='str')
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]): 
            x_d=d[i][j][k]
            if x_d > d_min and x_d < d_mean:
                bonus[i][j][k]="B"
            elif x_d > d_mean and x_d < d_max:
                bonus[i][j][k]="D"
            elif x_d == d_mean:
                bonus[i][j][k]="C"
            elif x_d == d_min:
                bonus[i][j][k]="A"
            elif x_d == d_max:
                bonus[i][j][k]="E"
   

print("-bonus-\n",bonus)

-bonus-
 [[['D' 'B' 'B' 'B' 'B']
  ['D' 'D' 'B' 'A' 'B']
  ['D' 'B' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'E']
  ['D' 'B' 'D' 'D' 'D']]]
